/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The schema for the config.json file
 */
export interface Config {
  /**
   * Just used to stop VSCode being angry
   */
  $schema: string;
  /**
   * The username of the bot owner
   */
  appOwnerUsername: string;
  /**
   * The ID of the bot owner
   */
  appOwnerId: string;
  /**
   * The bot token
   */
  token: string;
  /**
   * The bot's client ID
   */
  clientId: string;
  /**
   * Properties and options of the database to use. See https://sequelize.org for more info
   */
  database: {
    /**
     * Username
     */
    username: string;
    /**
     * User's password
     */
    password: string;
    /**
     * Host IP
     */
    host?: string;
    /**
     * Port number
     */
    port?: number;
    /**
     * Database name
     */
    name?: string;
    /**
     * Database dialect (MySQL, SQLite, etc.)
     */
    dialect: "mysql" | "sqlite3" | "db2" | "mariadb" | "mssql" | "postgres" | "snowflake";
    /**
     * Dialect-specific options
     */
    dialectOptions?: {
      [k: string]: unknown;
    };
  };
}
