/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The schema for the config.json file
 */
export interface Config {
  /**
   * Just used to stop VSCode being angry
   */
  $schema: string;
  /**
   * The username of the bot owner
   */
  appOwnerUsername: string;
  /**
   * The ID of the bot owner
   */
  appOwnerId: string;
  /**
   * The bot token
   */
  token: string;
  /**
   * The bot's client ID
   */
  clientId: string;
  /**
   * Properties and options of the database (MySQL only) to use. See https://sequelize.org for more info
   */
  database: {
    /**
     * Username
     */
    username: string;
    /**
     * User's password
     */
    password: string;
    /**
     * Host IP
     */
    host?: string;
    /**
     * Port number
     */
    port?: number;
    /**
     * Database name
     */
    name?: string;
  };
  /**
   * A list of user IDs that are allowed to restart the bot
   */
  allowedRestartUsers?: string[];
  /**
   * Properties and options for the development bot. These are not used in production. Used for testing and debugging purposes.
   */
  dev?: {
    /**
     * The development bot token
     */
    token: string;
    /**
     * The development bot's client ID
     */
    clientId: string;
    /**
     * The ID of the development server (where to register dev commands)
     */
    devServerId?: string;
  };
}
